apiVersion: apps/v1
kind: Deployment
metadata:
  name: evalio-frontend
  namespace: evalio
  labels:
    app: evalio-frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: evalio-frontend
  template:
    metadata:
      labels:
        app: evalio-frontend
    spec:
      containers:
        - name: evalio-frontend
          image: krishanand01/evalio-frontend:v1.4
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: "5m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evalio-backend
  namespace: evalio
  labels:
    app: evalio-backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: evalio-backend
  template:
    metadata:
      labels:
        app: evalio-backend
    spec:
      containers:
        - name: evalio-backend
          image: krishanand01/evalio-backend:v1.4.2
          ports:
            - containerPort: 3000
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              cpu: "5m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "512Mi"
          volumeMounts:
            - name: env-file
              mountPath: /app/apps/backend/.env
              subPath: env
      volumes:
        - name: env-file
          secret:
            secretName: evalio-backend-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: evalio

spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: Always

          ports:
            - containerPort: 6379

          resources:
            requests:
              cpu: "5m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"

          volumeMounts:
            - name: redis-data
              mountPath: /data

      volumes:
        - name: redis-data
          emptyDir: {}
